In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Beverage (1).csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol    quality  
0         8.8     Normal  
1         9.5     Normal  
2        10.1     Normal  
3         9.9     Normal  
4         9.9     Normal  
...       ...        ...  
4893     11.2     Normal  
4894      9.6     Normal  
4895      9.4     Normal  
4896     12.8  Excellent  
4897     11.8     Normal  

[4898 rows x 12 columns]

In [ ]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
df.duplicated().sum()

937

In [ ]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3961 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         3961 non-null   float64
 1   volatile acidity      3961 non-null   float64
 2   citric acid           3961 non-null   float64
 3   residual sugar        3961 non-null   float64
 4   chlorides             3961 non-null   float64
 5   free sulfur dioxide   3961 non-null   float64
 6   total sulfur dioxide  3961 non-null   float64
 7   density               3961 non-null   float64
 8   pH                    3961 non-null   float64
 9   sulphates             3961 non-null   float64
 10  alcohol               3961 non-null   float64
 11  quality               3961 non-null   object 
dtypes: float64(11), object(1)
memory usage: 402.3+ KB


In [ ]:
df['quality'].value_counts()

quality
Normal       2963
Excellent     825
Poor          173
Name: count, dtype: int64

In [ ]:
df['quality'] = df['quality'].map({'Normal':1, 'Excellent':2, 'Poor':0})

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['quality'] = le.fit_transform(df['quality'])

df['quality'].value_counts()

quality
1    2963
2     825
0     173
Name: count, dtype: int64

In [ ]:
df['fixed acidity'].value_counts()

fixed acidity
6.8     241
6.6     238
6.4     224
6.9     191
6.7     190
       ... 
4.6       1
11.8      1
14.2      1
10.7      1
3.9       1
Name: count, Length: 68, dtype: int64

In [ ]:
X = df.drop(columns='quality')
y = df['quality']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
print(X.shape)
print(y.shape)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3961, 11)
(3961,)
(3168, 11)
(3168,)
(793, 11)
(793,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

def LR(X_train, X_test, y_train, y_test):
  LogReg = LogisticRegression()

  LogReg.fit(X_train, y_train)
  y_pred = LogReg.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
LR(X_train, X_test, y_train, y_test)

[[  0  27   1]
 [  0 576  20]
 [  0 145  24]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        28
           1       0.77      0.97      0.86       596
           2       0.53      0.14      0.22       169

    accuracy                           0.76       793
   macro avg       0.43      0.37      0.36       793
weighted avg       0.69      0.76      0.69       793



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

In [ ]:
cor = df.corr()

In [ ]:
cor_1 = cor[abs(cor['quality'])>0.05]
cor_1

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.019214     0.298959   
volatile acidity          -0.019214          1.000000    -0.163228   
residual sugar             0.083620          0.098340     0.106269   
chlorides                  0.024036          0.086287     0.132590   
total sulfur dioxide       0.082425          0.102315     0.122845   
density                    0.266091          0.060603     0.160076   
pH                        -0.431274         -0.046954    -0.183015   
alcohol                   -0.110788          0.046815    -0.076514   
quality                   -0.112778         -0.134616    -0.000151   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.083620   0.024036            -0.058396   
volatile acidity            0.098340   0.086287            -0.102471   
residual sugar              1.000000   0.076091             0.306835   
chlorides                   0.076091   1.000000             0.101272   
total sulfur dioxide        0.409583   0.191145             0.619437   
density                     0.820498   0.253088             0.294638   
pH                         -0.165997  -0.090573            -0.007750   
alcohol                    -0.398167  -0.356928            -0.251768   
quality                    -0.095588  -0.180858             0.024868   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                     0.082425  0.266091 -0.431274  -0.017453   
volatile acidity                  0.102315  0.060603 -0.046954  -0.021150   
residual sugar                    0.409583  0.820498 -0.165997  -0.020503   
chlorides                         0.191145  0.253088 -0.090573   0.017871   
total sulfur dioxide              1.000000  0.536868  0.008239   0.136544   
density                           0.536868  1.000000 -0.063734   0.082048   
pH                                0.008239 -0.063734  1.000000   0.142353   
alcohol                          -0.446643 -0.760162  0.093095  -0.022850   
quality                          -0.138183 -0.285255  0.106079   0.048410   

                       alcohol   quality  
fixed acidity        -0.110788 -0.112778  
volatile acidity      0.046815 -0.134616  
residual sugar       -0.398167 -0.095588  
chlorides            -0.356928 -0.180858  
total sulfur dioxide -0.446643 -0.138183  
density              -0.760162 -0.285255  
pH                    0.093095  0.106079  
alcohol               1.000000  0.385087  
quality               0.385087  1.000000

In [ ]:
cor_2 = cor[abs(cor['quality'])>0.1]

In [ ]:
lsFeat_1 = list(cor_1['quality'].index)
lsFeat_2 = list(cor_2['quality'].index)

In [ ]:
df_1 = df[lsFeat_1]
df_2 = df[lsFeat_2]

In [ ]:
df_1

fixed acidity  volatile acidity  residual sugar  chlorides  \
0               7.0              0.27            20.7      0.045   
1               6.3              0.30             1.6      0.049   
2               8.1              0.28             6.9      0.050   
3               7.2              0.23             8.5      0.058   
6               6.2              0.32             7.0      0.045   
...             ...               ...             ...        ...   
4893            6.2              0.21             1.6      0.039   
4894            6.6              0.32             8.0      0.047   
4895            6.5              0.24             1.2      0.041   
4896            5.5              0.29             1.1      0.022   
4897            6.0              0.21             0.8      0.020   

      total sulfur dioxide  density    pH  alcohol  quality  
0                    170.0  1.00100  3.00      8.8        1  
1                    132.0  0.99400  3.30      9.5        1  
2                     97.0  0.99510  3.26     10.1        1  
3                    186.0  0.99560  3.19      9.9        1  
6                    136.0  0.99490  3.18      9.6        1  
...                    ...      ...   ...      ...      ...  
4893                  92.0  0.99114  3.27     11.2        1  
4894                 168.0  0.99490  3.15      9.6        1  
4895                 111.0  0.99254  2.99      9.4        1  
4896                 110.0  0.98869  3.34     12.8        2  
4897                  98.0  0.98941  3.26     11.8        1  

[3961 rows x 9 columns]

In [ ]:
df_2

fixed acidity  volatile acidity  chlorides  total sulfur dioxide  \
0               7.0              0.27      0.045                 170.0   
1               6.3              0.30      0.049                 132.0   
2               8.1              0.28      0.050                  97.0   
3               7.2              0.23      0.058                 186.0   
6               6.2              0.32      0.045                 136.0   
...             ...               ...        ...                   ...   
4893            6.2              0.21      0.039                  92.0   
4894            6.6              0.32      0.047                 168.0   
4895            6.5              0.24      0.041                 111.0   
4896            5.5              0.29      0.022                 110.0   
4897            6.0              0.21      0.020                  98.0   

      density    pH  alcohol  quality  
0     1.00100  3.00      8.8        1  
1     0.99400  3.30      9.5        1  
2     0.99510  3.26     10.1        1  
3     0.99560  3.19      9.9        1  
6     0.99490  3.18      9.6        1  
...       ...   ...      ...      ...  
4893  0.99114  3.27     11.2        1  
4894  0.99490  3.15      9.6        1  
4895  0.99254  2.99      9.4        1  
4896  0.98869  3.34     12.8        2  
4897  0.98941  3.26     11.8        1  

[3961 rows x 8 columns]

In [ ]:
X1 = df_1.drop(columns='quality')
y1 = df['quality']

X2 = df_2.drop(columns='quality')
y2 = df['quality']

In [ ]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X1, y1, test_size = 0.2)

X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X2, y2, test_size = 0.2)

In [ ]:
print(X1.shape)
print(y1.shape)
print(X_train_1.shape)
print(y_train_1.shape)
print(X_test_1.shape)
print(y_test_1.shape)

(3961, 8)
(3961,)
(3168, 8)
(3168,)
(793, 8)
(793,)


In [ ]:
print(X2.shape)
print(y2.shape)
print(X_train_2.shape)
print(y_train_2.shape)
print(X_test_2.shape)
print(y_test_2.shape)

(3961, 7)
(3961,)
(3168, 7)
(3168,)
(793, 7)
(793,)


In [ ]:
LR(X_train_1, X_test_1, y_train_1, y_test_1)

[[  2  29   1]
 [  1 586  24]
 [  0 123  27]]
              precision    recall  f1-score   support

           0       0.67      0.06      0.11        32
           1       0.79      0.96      0.87       611
           2       0.52      0.18      0.27       150

    accuracy                           0.78       793
   macro avg       0.66      0.40      0.42       793
weighted avg       0.74      0.78      0.72       793



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
LR(X_train_2, X_test_2, y_train_2, y_test_2)

[[  0  35   0]
 [  0 556  24]
 [  0 127  51]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        35
           1       0.77      0.96      0.86       580
           2       0.68      0.29      0.40       178

    accuracy                           0.77       793
   macro avg       0.48      0.42      0.42       793
weighted avg       0.72      0.77      0.72       793



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit